name: Open URLs with Python

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 * * * *'  # This will run the workflow every hour. Adjust the schedule as needed.

jobs:
  open-urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script
        run: python open_urls.py
